version: '3.7'

services:
  api-server:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    restart: always  
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8090/api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api-server
    networks:
      - frontend

networks:
  backend:
  frontend:
